"""add api tokens

Revision ID: 329197551e25
Revises: 26dc963beb2f
Create Date: 2026-08-16 00:45:24.000535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '329197551e25'
down_revision: Union[str, Sequence[str], None] = '26dc963beb2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apitoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['localuser.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apitoken', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apitoken_token_hash'), ['token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_apitoken_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apitoken', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apitoken_user_id'))
        batch_op.drop_index(batch_op.f('ix_apitoken_token_hash'))

    op.drop_table('apitoken')
    # ### end Alembic commands ###
